### ISSUE TITLE
Gas mask crafting bug

### ISSUE THREAD

**Issue by paccojl** [NoImageAvailable/CombatExtendedGuns#26]
Can't craft gas mask.
Error log on crafting start:

> MakeThing error: Tried to make UnfinishedMetallicTechArmor from Chemfuel which is not a stuff. Assigning default.
> Verse.Log:Error(String, Boolean)
> Verse.ThingMaker:MakeThing(ThingDef, ThingDef)
> Verse.AI.<MakeUnfinishedThingIfNeeded>c__AnonStorey0:<>m__0()
> Verse.AI.JobDriver:TryActuallyStartNextToil()
> Verse.AI.JobDriver:ReadyForNextToil()
> Verse.AI.JobDriver:Notify_PatherArrived()
> Verse.AI.Pawn_PathFollower:PatherArrived()
> Verse.AI.Pawn_PathFollower:StartPath(LocalTargetInfo, PathEndMode)
> Verse.AI.<GotoThing>c__AnonStorey0:<>m__0()
> Verse.AI.JobDriver:TryActuallyStartNextToil()
> Verse.AI.JobDriver:ReadyForNextToil()
> Verse.AI.JobDriver:TryActuallyStartNextToil()
> Verse.AI.JobDriver:ReadyForNextToil()
> Verse.AI.JobDriver:TryActuallyStartNextToil()
> Verse.AI.JobDriver:ReadyForNextToil()
> Verse.AI.JobDriver:TryActuallyStartNextToil()
> Verse.AI.JobDriver:ReadyForNextToil()
> Verse.AI.JobDriver:Notify_PatherArrived()
> Verse.AI.Pawn_PathFollower:PatherArrived()
> Verse.AI.Pawn_PathFollower:TryEnterNextPathCell()
> Verse.AI.Pawn_PathFollower:PatherTick()
> Verse.Pawn:Tick()
> Verse.TickList:Tick()
> Verse.TickManager:DoSingleTick()
> Verse.TickManager:TickManagerUpdate()
> Verse.Game:UpdatePlay()
> Verse.Root_Play:Update()

Error log on crafting end:

> JobDriver threw exception in initAction for pawn O'Neill driver=JobDriver_DoBill (toilIndex=13) driver.job=(DoBill (Job_35680) A=Thing_TableMachining37733 B=Thing_UnfinishedMetallicTechArmor54815 C=(148, 0, 168)) lastJobGiver=RimWorld.JobGiver_Work
> System.InvalidOperationException: Operation is not valid due to the current state of the object
>   at System.Linq.Enumerable.First[Thing] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback) [0x00000] in <filename unknown>:0 
>   at System.Linq.Enumerable.First[Thing] (IEnumerable`1 source, System.Func`2 predicate) [0x00000] in <filename unknown>:0 
>   at Verse.AI.Toils_Recipe.CalculateDominantIngredient (Verse.AI.Job job, System.Collections.Generic.List`1 ingredients) [0x00000] in <filename unknown>:0 
>   at Verse.AI.Toils_Recipe+<FinishRecipeAndStartStoringProduct>c__AnonStorey2.<>m__0 () [0x00000] in <filename unknown>:0 
>   at Verse.AI.JobDriver.TryActuallyStartNextToil () [0x00000] in <filename unknown>:0 
> Verse.Log:Error(String, Boolean)
> Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)
> Verse.AI.JobDriver:TryActuallyStartNextToil()
> Verse.AI.JobDriver:ReadyForNextToil()
> Verse.AI.<DoRecipeWork>c__AnonStorey1:<>m__1()
> Verse.AI.JobDriver:DriverTick()
> Verse.AI.Pawn_JobTracker:JobTrackerTick()
> Verse.Pawn:Tick()
> Verse.TickList:Tick()
> Verse.TickManager:DoSingleTick()
> Verse.TickManager:TickManagerUpdate()
> Verse.Game:UpdatePlay()
> Verse.Root_Play:Update()
>

**Comment by NoImageAvailable** [comment]
You're in the wrong repo
